### ISSUE TITLE
CachyOS iso install errors

### ISSUE THREAD

**Issue by Lukas0120** [ptr1337/linux-cacule#11]
Is the cachyos distro still maintained? Tried to install the iso but getting some errors regarding the mirrorlists, same when trying to add your repo

**Comment by ptr1337** [comment]
Heya, 

if you got discord consider to join our channel: 

https://discord.gg/qVhfwpTw

another option would be using our forum: 

https://forum.cachyos.org/

its not completly done but useable. 

Because the rpeo, it is tested (also fixed again since yesterday due some changes) 

https://wiki.cachyos.org/en/home/Repo

Because the ISO, we fixed the CLI-Installer, youll find the latest ISO here:

https://sourceforge.net/projects/cachyos-arch/files/cli-installer/

Regards and tell me if everything is working.

**Comment by ptr1337** [comment]
Just did a install now, since my dkms broke due ago + lto. 

Worked without problems the installer

**Comment by ptr1337** [comment]
@Lukas0120 

Okay some things are missing because we reworked the repo. But general it works. 

Ill update it today
