### ISSUE TITLE
Usb not work on linux 5.15

### ISSUE THREAD

**Issue by AldairSoraka** [ptr1337/linux-cacule#17]
Hello i have artix linux and when i updated to Linux-Cacule Kernel 5.15 my usb devices did not work, i already try to connect them to other ports but nothing has happen

**Comment by evencarmer** [comment]
Same for me on Arch. Wireless mouse. No issues on previous kernels and linux-tkg-bmq 5.15 working fine 
Lenovo x230

**Comment by ptr1337** [comment]
Its only since 5.15 ? 

Did you already updated the kernels to the latest commits?  

Please also take a watch here:

https://github.com/CachyOS/linux-cachyos

Its much work to update both repos and the complete aur in one time. 

So far, from other which got also this issue, seems to be solved with the latest updates.

**Comment by ptr1337** [comment]
But let me push the latest "fixes". Gonna work on it.

**Comment by ptr1337** [comment]
Pushed now on both repos. 
Compiled on the server will be with 5.15.1 again.

**Comment by AldairSoraka** [comment]
oh sorry I left this open but apparently it resolved only after a few hours, maybe I had something loaded in the ram
