### ISSUE TITLE
Patch suggestion

### ISSUE THREAD

**Issue by sm9cc** [ptr1337/linux-cacule#6]
Hi there, this patch seems quite useful,- [hakavlad/le9-patch](https://github.com/hakavlad/le9-patch), I have quite bad performance issues under low memory so I found this when I was looking for solutions.

It would be nice if you could look into adding it.

I am using **5.13.2-rt1-1-cacule-rdb-rt** currently.

Thanks!

**Comment by ptr1337** [comment]
Hey @SM9CC,

Thanks for your suggestion, in all other kernels I using a little changed patchiest, which works together with the LRU patches. 

I thought about canceling to support 5.13 RT Kernels, but if there is still interest I will still maintain it. 
I wanted to maintain only the 5.10LTS kernel, since the RT patchiest is much more frequently updated.

But I will update the 5.13 RT Kernel tomorrow and also add the le9 patch.

Regards,.

**Comment by sm9cc** [comment]
Much appreciated, also, I personally don't mind running an LTS kernel if that saves you some work.

Thanks a lot.

**Comment by ptr1337** [comment]
> Much appreciated, also, I personally don't mind running an LTS kernel if that saves you some work.
> 
> Thanks a lot.

Going to update today the LTS. with the lates le9.

**Comment by sm9cc** [comment]
Great, thank you!

**Comment by ptr1337** [comment]
@SM9CC 

Got updated, used his new patch and some default values. the anon value isnt touched you can change every value in sysctl. 

https://github.com/hakavlad/le9-patch/blob/main/le9eb_patches/le9eb-5.10.patch
